// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message containing the user's name.
type HelloAgainRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloAgainRequest) Reset()         { *m = HelloAgainRequest{} }
func (m *HelloAgainRequest) String() string { return proto.CompactTextString(m) }
func (*HelloAgainRequest) ProtoMessage()    {}
func (*HelloAgainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{2}
}

func (m *HelloAgainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloAgainRequest.Unmarshal(m, b)
}
func (m *HelloAgainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloAgainRequest.Marshal(b, m, deterministic)
}
func (m *HelloAgainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloAgainRequest.Merge(m, src)
}
func (m *HelloAgainRequest) XXX_Size() int {
	return xxx_messageInfo_HelloAgainRequest.Size(m)
}
func (m *HelloAgainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloAgainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloAgainRequest proto.InternalMessageInfo

func (m *HelloAgainRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloAgainRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

// The response message containing the greetings
type HelloAgainReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DoubleNumber         int32    `protobuf:"varint,2,opt,name=doubleNumber,proto3" json:"doubleNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloAgainReply) Reset()         { *m = HelloAgainReply{} }
func (m *HelloAgainReply) String() string { return proto.CompactTextString(m) }
func (*HelloAgainReply) ProtoMessage()    {}
func (*HelloAgainReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{3}
}

func (m *HelloAgainReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloAgainReply.Unmarshal(m, b)
}
func (m *HelloAgainReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloAgainReply.Marshal(b, m, deterministic)
}
func (m *HelloAgainReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloAgainReply.Merge(m, src)
}
func (m *HelloAgainReply) XXX_Size() int {
	return xxx_messageInfo_HelloAgainReply.Size(m)
}
func (m *HelloAgainReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloAgainReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloAgainReply proto.InternalMessageInfo

func (m *HelloAgainReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloAgainReply) GetDoubleNumber() int32 {
	if m != nil {
		return m.DoubleNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*HelloAgainRequest)(nil), "helloworld.HelloAgainRequest")
	proto.RegisterType((*HelloAgainReply)(nil), "helloworld.HelloAgainReply")
}

func init() { proto.RegisterFile("helloworld/helloworld.proto", fileDescriptor_73149fedf49f4319) }

var fileDescriptor_73149fedf49f4319 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0xa2, 0xad, 0x0e, 0x15, 0x71, 0x0f, 0x25, 0x34, 0x08, 0x65, 0x0f, 0xd2, 0x4b, 0x12,
	0x50, 0xbc, 0x2a, 0xb6, 0x87, 0x8a, 0x50, 0x0d, 0xf1, 0x20, 0x78, 0xdb, 0xb4, 0x43, 0x12, 0xd8,
	0xec, 0xc6, 0x4d, 0x82, 0xee, 0x9f, 0xf8, 0xb9, 0x92, 0xb5, 0x21, 0x2b, 0x6a, 0x6f, 0xf3, 0x66,
	0xde, 0x7b, 0xbb, 0x33, 0x0f, 0xbc, 0x0c, 0x39, 0x97, 0xef, 0x52, 0xf1, 0x4d, 0xd8, 0x97, 0x41,
	0xa9, 0x64, 0x2d, 0x09, 0xf4, 0x1d, 0x4a, 0x61, 0x74, 0xdf, 0xa2, 0x18, 0xdf, 0x1a, 0xac, 0x6a,
	0x42, 0xe0, 0x40, 0xb0, 0x02, 0x5d, 0x67, 0xea, 0xcc, 0x8e, 0x63, 0x53, 0xd3, 0x0b, 0x80, 0x2d,
	0xa7, 0xe4, 0x9a, 0xb8, 0x30, 0x2c, 0xb0, 0xaa, 0x58, 0xda, 0x91, 0x3a, 0x48, 0x6f, 0xe1, 0xcc,
	0xf0, 0xee, 0x52, 0x96, 0x8b, 0x1d, 0x86, 0x64, 0x0c, 0x03, 0xd1, 0x14, 0x09, 0x2a, 0x77, 0x7f,
	0xea, 0xcc, 0x0e, 0xe3, 0x2d, 0xa2, 0x4f, 0x70, 0x6a, 0x1b, 0xec, 0x7c, 0x8d, 0x50, 0x18, 0x6d,
	0x64, 0x93, 0x70, 0x7c, 0xb4, 0xad, 0x7e, 0xf4, 0x2e, 0x3f, 0x1d, 0x18, 0x2e, 0x15, 0x62, 0x8d,
	0x8a, 0xdc, 0xc0, 0xd1, 0x33, 0xd3, 0xc6, 0x9f, 0xb8, 0x81, 0x75, 0x14, 0x7b, 0xff, 0xc9, 0xf8,
	0x8f, 0x49, 0xc9, 0x35, 0xdd, 0x23, 0x2b, 0x38, 0xe9, 0xf4, 0xe6, 0x7f, 0xe4, 0xfc, 0x17, 0xd5,
	0x5e, 0x7c, 0xe2, 0xfd, 0x37, 0x36, 0x76, 0xf3, 0x14, 0xbc, 0x5c, 0x06, 0xa9, 0x2a, 0xd7, 0x01,
	0x7e, 0xb0, 0xa2, 0xe4, 0x58, 0x59, 0x82, 0xf9, 0xf7, 0x21, 0x5e, 0xda, 0x3a, 0x6a, 0x43, 0x8b,
	0x9c, 0xd7, 0xeb, 0x34, 0xaf, 0xb3, 0x26, 0x09, 0xd6, 0xb2, 0x08, 0x17, 0x19, 0x0a, 0xff, 0x21,
	0x17, 0xbe, 0x6e, 0x98, 0x08, 0x97, 0x71, 0xb4, 0xf0, 0x57, 0xba, 0x97, 0x58, 0x99, 0x27, 0x03,
	0x13, 0xfa, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xbe, 0x56, 0xe3, 0x13, 0x02, 0x00,
	0x00,
}
